### ISSUE TITLE
Allow Command Editing

### ISSUE THREAD

**Issue by Skillz4Killz** [eritbh/yuuko#38]
Sometimes a user can make a silly typo and to prevent them from having to remake the entire command again, having the ability to reprocess a message on `messageUpdate` would be really cool. 

From a developer perspective, this becomes really useful for the `debug` command as you can easily, edit the message incase you want to go 1 layer deeper into the object.

**Comment by eritbh** [comment]
I guess this is more or less resolved now - you can manually call `Client#processCommand` on a message from anywhere you want, so you can allow handling commands for edited messages by adding some logic for it in a `messageUpdate` event listener.

I'm not super keen on building more direct support for this into Yuuko anymore, mostly because there's lots of different ways to implement this. Do you allow command edits only on messages that didn't previously have valid commands? How long after a message is sent do you pick up edits for it as potential command triggers? `processCommand` being available, combined with `ClientOptions#disableDefaultMessageListener`, makes it possible to implement any command editing system you want, but this is a relatively niche use-case and I don't want to introduce opinionated code to this project when I don't actually have a preference for a default strategy myself.
